---
- name: AWS deploy
  hosts: aws
  tasks:
    - name: Install aptitude using apt
      become: true
      become_user: root
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      become: true
      become_user: root
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      become: true
      become_user: root
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: true
      become_user: root
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      become: true
      become_user: root
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      become: true
      become_user: root
      pip:
        name: docker

    - name: application container
      become: true
      become_user: root
      docker_container:
        name: my-webapp
        image: chyuan530/devops-final:10
        state: started
        restart: yes
        pull: yes
