---
- name: AWS deploy
  hosts: aws
  tasks:
    - name: application container
      docker:
        name: my-webapp
        image: chyuan530/devops-final
        state: reloaded
        pull: always
