---
- name: AWS deploy
  hosts: aws
  tasks:
    - name: application container
      docker_container:
        name: my-webapp
        image: chyuan530/devops-final
        state: started
        restart: yes
        pull: yes
